///
/// Code generated by jsonToDartModel http://json.fluttergeeks.in/
///
class NotificationResponseDataLinks {
/*
{
  "first": "https://inventory.grozaarbd.com/api/v1/delivery-man/get-notifications?page=1",
  "last": "https://inventory.grozaarbd.com/api/v1/delivery-man/get-notifications?page=3",
  "prev": null,
  "next": "https://inventory.grozaarbd.com/api/v1/delivery-man/get-notifications?page=2"
}
*/

  String? first;
  String? last;
  String? prev;
  String? next;

  NotificationResponseDataLinks({
    this.first,
    this.last,
    this.prev,
    this.next,
  });
  NotificationResponseDataLinks.fromJson(Map<String, dynamic> json) {
    first = json['first']?.toString();
    last = json['last']?.toString();
    prev = json['prev']?.toString();
    next = json['next']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['first'] = first;
    data['last'] = last;
    data['prev'] = prev;
    data['next'] = next;
    return data;
  }
}

class NotificationResponseDataMeta {
/*
{
  "current_page": 1,
  "from": 1,
  "last_page": 3,
  "per_page": 10,
  "to": 10,
  "total": 26
}
*/

  String? currentPage;
  String? from;
  String? lastPage;
  String? perPage;
  String? to;
  String? total;

  NotificationResponseDataMeta({
    this.currentPage,
    this.from,
    this.lastPage,
    this.perPage,
    this.to,
    this.total,
  });
  NotificationResponseDataMeta.fromJson(Map<String, dynamic> json) {
    currentPage = json['current_page']?.toString();
    from = json['from']?.toString();
    lastPage = json['last_page']?.toString();
    perPage = json['per_page']?.toString();
    to = json['to']?.toString();
    total = json['total']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['current_page'] = currentPage;
    data['from'] = from;
    data['last_page'] = lastPage;
    data['per_page'] = perPage;
    data['to'] = to;
    data['total'] = total;
    return data;
  }
}

class NotificationResponseDataData {
/*
{
  "id": "01f1fb86-04f7-435f-9d1a-1feffb19d030",
  "title": "Order delivered",
  "message": "Order Successfully Delivered. Invoice id: INV-5629-0034",
  "order_id": 35,
  "notify_type": "order",
  "read_at": null,
  "created_date": "2025-06-02 12:06 PM",
  "user_id": 7
}
*/

  String? id;
  String? title;
  String? message;
  String? orderId;
  String? notifyType;
  String? readAt;
  String? createdDate;
  String? userId;

  NotificationResponseDataData({
    this.id,
    this.title,
    this.message,
    this.orderId,
    this.notifyType,
    this.readAt,
    this.createdDate,
    this.userId,
  });
  NotificationResponseDataData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    title = json['title']?.toString();
    message = json['message']?.toString();
    orderId = json['order_id']?.toString();
    notifyType = json['notify_type']?.toString();
    readAt = json['read_at']?.toString();
    createdDate = json['created_date']?.toString();
    userId = json['user_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['message'] = message;
    data['order_id'] = orderId;
    data['notify_type'] = notifyType;
    data['read_at'] = readAt;
    data['created_date'] = createdDate;
    data['user_id'] = userId;
    return data;
  }
}

class NotificationResponseData {
/*
{
  "data": [
    {
      "id": "01f1fb86-04f7-435f-9d1a-1feffb19d030",
      "title": "Order delivered",
      "message": "Order Successfully Delivered. Invoice id: INV-5629-0034",
      "order_id": 35,
      "notify_type": "order",
      "read_at": null,
      "created_date": "2025-06-02 12:06 PM",
      "user_id": 7
    }
  ],
  "meta": {
    "current_page": 1,
    "from": 1,
    "last_page": 3,
    "per_page": 10,
    "to": 10,
    "total": 26
  },
  "links": {
    "first": "https://inventory.grozaarbd.com/api/v1/delivery-man/get-notifications?page=1",
    "last": "https://inventory.grozaarbd.com/api/v1/delivery-man/get-notifications?page=3",
    "prev": null,
    "next": "https://inventory.grozaarbd.com/api/v1/delivery-man/get-notifications?page=2"
  }
}
*/

  List<NotificationResponseDataData?>? data;
  NotificationResponseDataMeta? meta;
  NotificationResponseDataLinks? links;

  NotificationResponseData({
    this.data,
    this.meta,
    this.links,
  });
  NotificationResponseData.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null && (json['data'] is List)) {
      final v = json['data'];
      final arr0 = <NotificationResponseDataData>[];
      v.forEach((v) {
        arr0.add(NotificationResponseDataData.fromJson(v));
      });
      this.data = arr0;
    }
    meta = (json['meta'] != null && (json['meta'] is Map)) ? NotificationResponseDataMeta.fromJson(json['meta']) : null;
    links = (json['links'] != null && (json['links'] is Map)) ? NotificationResponseDataLinks.fromJson(json['links']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (links != null) {
      data['links'] = links!.toJson();
    }
    return data;
  }
}

class NotificationResponse {
/*
{
  "success": true,
  "message": "Success",
  "data": {
    "data": [
      {
        "id": "01f1fb86-04f7-435f-9d1a-1feffb19d030",
        "title": "Order delivered",
        "message": "Order Successfully Delivered. Invoice id: INV-5629-0034",
        "order_id": 35,
        "notify_type": "order",
        "read_at": null,
        "created_date": "2025-06-02 12:06 PM",
        "user_id": 7
      }
    ],
    "meta": {
      "current_page": 1,
      "from": 1,
      "last_page": 3,
      "per_page": 10,
      "to": 10,
      "total": 26
    },
    "links": {
      "first": "https://inventory.grozaarbd.com/api/v1/delivery-man/get-notifications?page=1",
      "last": "https://inventory.grozaarbd.com/api/v1/delivery-man/get-notifications?page=3",
      "prev": null,
      "next": "https://inventory.grozaarbd.com/api/v1/delivery-man/get-notifications?page=2"
    }
  }
}
*/

  bool? success;
  String? message;
  NotificationResponseData? data;

  NotificationResponse({
    this.success,
    this.message,
    this.data,
  });
  NotificationResponse.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    data = (json['data'] != null && (json['data'] is Map)) ? NotificationResponseData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
