///
/// Code generated by jsonToDartModel http://json.fluttergeeks.in/
///
class OrderResponseDataLinks {
/*
{
  "first": "https://inventory.grozaarbd.com/api/v1/delivery-man/get-order-request?page=1",
  "last": "https://inventory.grozaarbd.com/api/v1/delivery-man/get-order-request?page=1",
  "prev": null,
  "next": null
}
*/

  String? first;
  String? last;
  String? prev;
  String? next;

  OrderResponseDataLinks({
    this.first,
    this.last,
    this.prev,
    this.next,
  });
  OrderResponseDataLinks.fromJson(Map<String, dynamic> json) {
    first = json['first']?.toString();
    last = json['last']?.toString();
    prev = json['prev']?.toString();
    next = json['next']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['first'] = first;
    data['last'] = last;
    data['prev'] = prev;
    data['next'] = next;
    return data;
  }
}

class OrderResponseDataMeta {
/*
{
  "current_page": 1,
  "from": 1,
  "last_page": 1,
  "per_page": 20,
  "to": 2,
  "total": 2
}
*/

  String? currentPage;
  String? from;
  String? lastPage;
  String? perPage;
  String? to;
  String? total;

  OrderResponseDataMeta({
    this.currentPage,
    this.from,
    this.lastPage,
    this.perPage,
    this.to,
    this.total,
  });
  OrderResponseDataMeta.fromJson(Map<String, dynamic> json) {
    currentPage = json['current_page']?.toString();
    from = json['from']?.toString();
    lastPage = json['last_page']?.toString();
    perPage = json['per_page']?.toString();
    to = json['to']?.toString();
    total = json['total']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['current_page'] = currentPage;
    data['from'] = from;
    data['last_page'] = lastPage;
    data['per_page'] = perPage;
    data['to'] = to;
    data['total'] = total;
    return data;
  }
}

class OrderResponseDataDataCustomer {
/*
{
  "id": 4,
  "email": "restaurant@app.com",
  "phone": "+880162281992932",
  "type": "Restaurant",
  "avatar_url": "https://inventory.grozaarbd.com/storage/users/1745495591_800693140_4.jpg",
  "full_name": "rest live ",
  "manager_phone": "2342342",
  "restaurant_address": null,
  "total_order_amount": "767.53",
  "total_paid_amount": "767.53",
  "total_due_amount": "0.00"
}
*/

  String? id;
  String? email;
  String? phone;
  String? type;
  String? avatarUrl;
  String? fullName;
  String? managerPhone;
  String? restaurantAddress;
  String? totalOrderAmount;
  String? totalPaidAmount;
  String? totalDueAmount;

  OrderResponseDataDataCustomer({
    this.id,
    this.email,
    this.phone,
    this.type,
    this.avatarUrl,
    this.fullName,
    this.managerPhone,
    this.restaurantAddress,
    this.totalOrderAmount,
    this.totalPaidAmount,
    this.totalDueAmount,
  });
  OrderResponseDataDataCustomer.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    email = json['email']?.toString();
    phone = json['phone']?.toString();
    type = json['type']?.toString();
    avatarUrl = json['avatar_url']?.toString();
    fullName = json['full_name']?.toString();
    managerPhone = json['manager_phone']?.toString();
    restaurantAddress = json['restaurant_address']?.toString();
    totalOrderAmount = json['total_order_amount']?.toString();
    totalPaidAmount = json['total_paid_amount']?.toString();
    totalDueAmount = json['total_due_amount']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['email'] = email;
    data['phone'] = phone;
    data['type'] = type;
    data['avatar_url'] = avatarUrl;
    data['full_name'] = fullName;
    data['manager_phone'] = managerPhone;
    data['restaurant_address'] = restaurantAddress;
    data['total_order_amount'] = totalOrderAmount;
    data['total_paid_amount'] = totalPaidAmount;
    data['total_due_amount'] = totalDueAmount;
    return data;
  }
}

class OrderResponseDataData {
/*
{
  "id": 16,
  "invoice_no": "INV-2460-0015",
  "date": "2025-05-27",
  "time": "1 week ago",
  "order_items": 1,
  "customer": {
    "id": 4,
    "email": "restaurant@app.com",
    "phone": "+880162281992932",
    "type": "Restaurant",
    "avatar_url": "https://inventory.grozaarbd.com/storage/users/1745495591_800693140_4.jpg",
    "full_name": "rest live ",
    "manager_phone": "2342342",
    "restaurant_address": null,
    "total_order_amount": "767.53",
    "total_paid_amount": "767.53",
    "total_due_amount": "0.00"
  },
  "status": "Packaged"
}
*/

  String? id;
  String? invoiceNo;
  String? date;
  String? time;
  String? orderItems;
  OrderResponseDataDataCustomer? customer;
  String? status;

  OrderResponseDataData({
    this.id,
    this.invoiceNo,
    this.date,
    this.time,
    this.orderItems,
    this.customer,
    this.status,
  });
  OrderResponseDataData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    invoiceNo = json['invoice_no']?.toString();
    date = json['date']?.toString();
    time = json['time']?.toString();
    orderItems = json['order_items']?.toString();
    customer = (json['customer'] != null && (json['customer'] is Map)) ? OrderResponseDataDataCustomer.fromJson(json['customer']) : null;
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['invoice_no'] = invoiceNo;
    data['date'] = date;
    data['time'] = time;
    data['order_items'] = orderItems;
    if (customer != null) {
      data['customer'] = customer!.toJson();
    }
    data['status'] = status;
    return data;
  }
}

class OrderResponseData {
/*
{
  "data": [
    {
      "id": 16,
      "invoice_no": "INV-2460-0015",
      "date": "2025-05-27",
      "time": "1 week ago",
      "order_items": 1,
      "customer": {
        "id": 4,
        "email": "restaurant@app.com",
        "phone": "+880162281992932",
        "type": "Restaurant",
        "avatar_url": "https://inventory.grozaarbd.com/storage/users/1745495591_800693140_4.jpg",
        "full_name": "rest live ",
        "manager_phone": "2342342",
        "restaurant_address": null,
        "total_order_amount": "767.53",
        "total_paid_amount": "767.53",
        "total_due_amount": "0.00"
      },
      "status": "Packaged"
    }
  ],
  "meta": {
    "current_page": 1,
    "from": 1,
    "last_page": 1,
    "per_page": 20,
    "to": 2,
    "total": 2
  },
  "links": {
    "first": "https://inventory.grozaarbd.com/api/v1/delivery-man/get-order-request?page=1",
    "last": "https://inventory.grozaarbd.com/api/v1/delivery-man/get-order-request?page=1",
    "prev": null,
    "next": null
  }
}
*/

  List<OrderResponseDataData?>? data;
  OrderResponseDataMeta? meta;
  OrderResponseDataLinks? links;

  OrderResponseData({
    this.data,
    this.meta,
    this.links,
  });
  OrderResponseData.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null && (json['data'] is List)) {
      final v = json['data'];
      final arr0 = <OrderResponseDataData>[];
      v.forEach((v) {
        arr0.add(OrderResponseDataData.fromJson(v));
      });
      this.data = arr0;
    }
    meta = (json['meta'] != null && (json['meta'] is Map)) ? OrderResponseDataMeta.fromJson(json['meta']) : null;
    links = (json['links'] != null && (json['links'] is Map)) ? OrderResponseDataLinks.fromJson(json['links']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (links != null) {
      data['links'] = links!.toJson();
    }
    return data;
  }
}

class OrderResponse {
/*
{
  "success": true,
  "message": "Success",
  "data": {
    "data": [
      {
        "id": 16,
        "invoice_no": "INV-2460-0015",
        "date": "2025-05-27",
        "time": "1 week ago",
        "order_items": 1,
        "customer": {
          "id": 4,
          "email": "restaurant@app.com",
          "phone": "+880162281992932",
          "type": "Restaurant",
          "avatar_url": "https://inventory.grozaarbd.com/storage/users/1745495591_800693140_4.jpg",
          "full_name": "rest live ",
          "manager_phone": "2342342",
          "restaurant_address": null,
          "total_order_amount": "767.53",
          "total_paid_amount": "767.53",
          "total_due_amount": "0.00"
        },
        "status": "Packaged"
      }
    ],
    "meta": {
      "current_page": 1,
      "from": 1,
      "last_page": 1,
      "per_page": 20,
      "to": 2,
      "total": 2
    },
    "links": {
      "first": "https://inventory.grozaarbd.com/api/v1/delivery-man/get-order-request?page=1",
      "last": "https://inventory.grozaarbd.com/api/v1/delivery-man/get-order-request?page=1",
      "prev": null,
      "next": null
    }
  }
}
*/

  bool? success;
  String? message;
  OrderResponseData? data;

  OrderResponse({
    this.success,
    this.message,
    this.data,
  });
  OrderResponse.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    data = (json['data'] != null && (json['data'] is Map)) ? OrderResponseData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
