///
/// Code generated by jsonToDartModel http://json.fluttergeeks.in/
///
class UserDetailsResponseData {
/*
{
  "id": 7,
  "email": "delivery_man@app.com",
  "phone": "+88032423",
  "type": "Delivery Man",
  "full_name": "delivery man live ",
  "total_order_amount": "0.00",
  "total_paid_amount": "0.00",
  "total_due_amount": "0.00"
}
*/

  String? id;
  String? email;
  String? phone;
  String? type;
  String? fullName;
  String? totalOrderAmount;
  String? totalPaidAmount;
  String? totalDueAmount;

  UserDetailsResponseData({
    this.id,
    this.email,
    this.phone,
    this.type,
    this.fullName,
    this.totalOrderAmount,
    this.totalPaidAmount,
    this.totalDueAmount,
  });
  UserDetailsResponseData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    email = json['email']?.toString();
    phone = json['phone']?.toString();
    type = json['type']?.toString();
    fullName = json['full_name']?.toString();
    totalOrderAmount = json['total_order_amount']?.toString();
    totalPaidAmount = json['total_paid_amount']?.toString();
    totalDueAmount = json['total_due_amount']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['email'] = email;
    data['phone'] = phone;
    data['type'] = type;
    data['full_name'] = fullName;
    data['total_order_amount'] = totalOrderAmount;
    data['total_paid_amount'] = totalPaidAmount;
    data['total_due_amount'] = totalDueAmount;
    return data;
  }
}

class UserDetailsResponse {
/*
{
  "success": true,
  "message": "Success",
  "data": {
    "id": 7,
    "email": "delivery_man@app.com",
    "phone": "+88032423",
    "type": "Delivery Man",
    "full_name": "delivery man live ",
    "total_order_amount": "0.00",
    "total_paid_amount": "0.00",
    "total_due_amount": "0.00"
  }
}
*/

  bool? success;
  String? message;
  UserDetailsResponseData? data;

  UserDetailsResponse({
    this.success,
    this.message,
    this.data,
  });
  UserDetailsResponse.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    data = (json['data'] != null && (json['data'] is Map)) ? UserDetailsResponseData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
